version: '3.8'

services:
  postgres:
    image: postgres
    container_name: poc-1-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=poc_1
    ports:
      - 5432:5432

  poc-1:
    build: .
    image: poc-1
    container_name: poc-1
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/poc_1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080